### ISSUE TITLE
Mount volume for server files

### ISSUE THREAD

**Issue by AsharS** [lloesche/valheim-server-docker#12]
It might make more sense to mount the volume of the server files as well instead of just the config folder. Currently, any time you have to recreate the container (changing env variables etc), it will redownload all server files.

I mapped this volume right now so I don't have to redownload when recreating the container:
`./server:/opt/valheim`

**Comment by lloesche** [comment]
By default Docker won't remove the container when you stop it so there's no need to redownload. All it'll do on startup then is validate that the files inside the container are up to date.

It's only when you run it via `docker --rm` that it will recreate a fresh container. In my service file I always remove old containers, because I'm running on a 10G fibre connection and don't mind the 1G download, but if traffic is metered or the connection not fast you might want to remove the `--rm` option from the service file.

**Comment by lloesche** [comment]
@AsharS heads up, I just pushed a change that requires you to change your volume mount from `/opt/valheim` to `/opt/valheim_dl` as that's where `steamcmd` from now on downloads the server to. This is in service of fixing another issue where the updater was not able to detect new versions.

**Comment by lloesche** [comment]
Fixed in https://github.com/lloesche/valheim-server-docker/pull/16

**Comment by AsharS** [comment]
@lloesche The container recreation will usually be an issue when using docker-compose and changing any of the configs (e.g. environment variables)

**Comment by lloesche** [comment]
@AsharS ah that makes sense. Let me know if you find any other incompatibilities. I find it super interesting how everyone's environments are slightly different and something that's no issue in mine can cause huge problems in someone else's and vice versa. Also feel free to send PRs if you find anything that needs improving. Again thanks for your input!
