### ISSUE TITLE
WhiteList only

### ISSUE THREAD

**Issue by OneGoogus** [lloesche/valheim-server-docker#122]
How do you configurate the server as a no password and whitelist only server?

**Comment by lloesche** [comment]
I have never tried it, but I suppose you could see what happens if you start the server with:
```
VALHEIM_PLUS=true
SERVER_PASS=""
VPCFG_Server_enabled=true
VPCFG_Server_enforceMod=false
VPCFG_Server_disableServerPassword=true
```
and add the client IDs to your `/config/permittedlist.txt` file.

**Comment by kachunkachunk** [comment]
I currently run with this, and just wanted to confirm that it works swimmingly. If you have `public -1` set among server runtime arguments, it will eventually lead to users trying to connect to what shows up as a password-less Valheim server. It's not really an issue, unless a stranger discovers an exploit or bug to bypss the permitted list and get in. I currently ship and inspect server logs to trend what versions connect, in the off chance that I might notice a new version appear. That'd prompt me that a server update may be ready.

Otherwise:
- Users _not_ in the permittedlist.txt file (randoms, friends you haven't added to your list) may see a "Banned" notification upon connecting. That can be alarming for some folks. ;)
- If Valheim Plus is enforcing the mod with `enforceMod=true`, and/or the connecting client is using a different version, they first see an `Incompatible Version` error upon connecting.

You can look up 17-digit Steam IDs [here](https://steamidfinder.com) or [here](https://steamid.io/lookup)
