### ISSUE TITLE
Disable auto update on restart

### ISSUE THREAD

**Issue by Panderine** [lloesche/valheim-server-docker#133]
Every time the server is started it auto updates. Is there any way to disable this on start?

**Comment by lloesche** [comment]
No, because the updater is what starts the server. You can of course fork the repo and modify it in any way that works for your use case.
To do so you could start in `supervisord.conf`. Disable the `valheim-updater` and set `autorestart=true` for the `valheim-server`. However then you have to manually ensure that on first/fresh start the server gets downloaded from Steam before the container tries to start it. The updater is what usually downloads the server if it doesn't exist.

**Comment by Panderine** [comment]
thanks!!
