### ISSUE TITLE
.new world files are sometimes left over after server shutdown

### ISSUE THREAD

**Issue by belleDESiRE** [lloesche/valheim-server-docker#145]
Sometimes when shutting down/restarting the server it does so while still creating the .new files in the world directory.
This leaves a partially saved file behind, which I guess could be/is? an incomplete save of the world

Looks to be more of a valheim dedicated server issue and not so much your docker image, but it might help if you wait for the files to be gone while shutting down/restarting (with a max timeout, to prevent deadlocks).

![image](https://user-images.githubusercontent.com/24789925/109771366-0376ed00-7bfd-11eb-8011-99d3fa1a6b12.png)

**Comment by lloesche** [comment]
Since I do not know why those `.new` files are being created I won't be handling them. The original dedicated server script has no special treatment or locking for those cases so I won't include any either. I rather trust that the devs will handle those files gracefully. Should they include special `.new` file handling into their own dedicated server start/stop scripts then we'll add the same functionality here.
