### ISSUE TITLE
Logout causes things to despawn

### ISSUE THREAD

**Issue by Reqteq** [lloesche/valheim-server-docker#160]
So if I log out after building something it despawns it, is this normal?

Here is the log
03/04/2021 07:05:06: Got status changed msg k_ESteamNetworkingConnectionState_None
03/04/2021 07:05:06: Destroying abandoned non persistent zdo -848292750:1 owner -848292750
03/04/2021 07:05:06: Disposing socket
03/04/2021 07:05:06: Disposing socket

**Comment by lloesche** [comment]
No that is not normal. When you build something it should persist in the world. In fact we have the problem on our server that we can not destroy anything and even useless materials that we dropped somewhere in the woods weeks ago are still there and litter the landscape.

From the log, I have no idea what a "zdo" is so I don't know what that message means exactly or if it relates to building at all.

**Comment by Reqteq** [comment]
Thanks for the reply. 

So what I notice is that it is actually destroying buildings/undoing any terraforming and the materials are lost in the process even though its in proximity to a workbench. 

This only started happening after the 0.147.3 update by the way.

**Comment by lloesche** [comment]
Interesting! I haven't checked since that update if our old stuff is still laying around in the woods. I know for sure that our town is where it's always been. As are all the outposts.

**Comment by ageisen2000** [comment]
I've had this issue when my game crashes as well. Sometimes I will also end up back at my base randomly.

One issue that's probably an in-game related bug and not an issue with this container is that if I restart the server it will lose all progress since the last sleep cycle.

@lloesche is there a way that I can force a server state save before any updates or any container restarts can happen?

**Comment by lloesche** [comment]
@ageisen2000 when you do a regular restart or shutdown or when an update restarts the server it will save the world. If it doesn't there's something wrong and we should try and figure out what it is.
If you are [an administrator](https://github.com/lloesche/valheim-server-docker#admin-commands) you can manually open the console in-game and enter `save` to have the world be saved.
You will see something like this in the server log when saving was successful:
```
03/11/2021 18:38:02: Saved 10406 zdos
03/11/2021 18:38:03: World saved ( 199.522ms )
```

Also note that when your Windows or Linux client crashes and you're getting reset that has nothing to do with the server. Your character and inventory is stored on the client only. On our server we've had people die somewhere in the wild, then crash, not being able to find their tombstone (because it wasn't marked on the client's map after the crash) and lose their entire inventory that way. Always backup your character locally!

**Comment by ageisen2000** [comment]
@lloesche is `docker-compose restart` the wrong way to do it? That's when I'm seeing issues.

I will lose about 5 mins of gameplay or so. I didn't know about the save command though, can this be run somehow through `docker-compose exec`? If so, I will just add that to my update and restart script.

**Comment by lloesche** [comment]
@ageisen2000 no the save command is an in-game admin command. See here for details: https://github.com/lloesche/valheim-server-docker#admin-commands

`docker-compose restart` is an okay command to restart everything. I'm saying "okay" because it will restart absolutely everything, not just the server. If you only wanted to restart the server `docker exec -it valheim-server supervisorctl restart valheim-server` should do the trick. Alternatively you can also set `SUPERVISOR_HTTP=true`, `SUPERVISOR_HTTP_PASS=somesecret` and start the container with `-p 9001:9001`. This will expose the Supervisor web UI. See https://github.com/lloesche/valheim-server-docker#supervisor for details.

Also check our latest compose file: https://github.com/lloesche/valheim-server-docker/blob/main/docker-compose.yaml

and see if you have that last line that we added in yours. We had reports from people that on their hardware the shutdown of the server took longer than the Docker timeout and then Docker hard killed their container. Maybe you're running into the same situation. With the `stop_grace_period: 2m` line the container is given up to 2 minutes to shut down which should be plenty (normal shutdown takes a few seconds).

**Comment by vPeteWalker** [comment]
> @ageisen2000 no the save command is an in-game admin command. See here for details: https://github.com/lloesche/valheim-server-docker#admin-commands
> 
> `docker-compose restart` is an okay command to restart everything. I'm saying "okay" because it will restart absolutely everything, not just the server. If you only wanted to restart the server `docker exec -it valheim-server supervisorctl restart valheim-server` should do the trick. Alternatively you can also set `SUPERVISOR_HTTP=true`, `SUPERVISOR_HTTP_PASS=somesecret` and start the container with `-p 9001:9001`. This will expose the Supervisor web UI. See https://github.com/lloesche/valheim-server-docker#supervisor for details.
> 
> Also check our latest compose file: https://github.com/lloesche/valheim-server-docker/blob/main/docker-compose.yaml
> 
> and see if you have that last line that we added in yours. We had reports from people that on their hardware the shutdown of the server took longer than the Docker timeout and then Docker hard killed their container. Maybe you're running into the same situation. With the `stop_grace_period: 2m` line the container is given up to 2 minutes to shut down which should be plenty (normal shutdown takes a few seconds).

Hey bud. I added the 3 supervisor entries into my ENV file, and also the port entry into my docker-compose file. I'm not able to connect to the supervisor page. I ensured I typed HTTP in the browser including the port... i.e. http://ip:9001/

Would appreciate your advice as to where I'm going wrong here. Thanks a ton.

```
valheim:
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    container_name: valheim
    env_file:
      - /$HOME/config/valheim/valheim.env
    ports:
      - 2455-2458:2455-2458/udp
      - 9001:9001/tcp
    volumes:
      - /$HOME/config/valheim:/config
    restart: always
    stop_grace_period: 2m
```

```
PUID=1000
PGID=1000
TZ=America/New_York
SERVER_NAME=SERVERNAME
WORLD_NAME=WORLDNAME
SERVER_PORT=2456
SERVER_PUBLIC=true
SERVER_PASS=PASSWORD
UPDATE_CRON='*/15 * * * *'
UPDATE_IF_IDLE=true
SUPERVISOR_HTTP_USER=admin
SUPERVISOR_HTTP=true
SUPERVISOR_HTTP_PASS=PASSWORD
BACKUPS_CRON='7 * * * *'
BACKUPS=true
BACKUPS_DIRECTORY=/config/backups
BACKUPS_MAX_AGE=30
DISCORD_WEBHOOK=https://discord.com/api/webhooks/.............
DISCORD_MESSAGE=Restarting Valheim server in 5 minutes!
PRE_BOOTSTRAP_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$(eval echo $DISCORD_MESSAGE)\"}" "$DISCORD_WEBHOOK"
```

**Comment by lloesche** [comment]
@vPeteWalker your config looks good. Are you on the latest version of the image? `docker pull lloesche/valheim-server:latest`

When you start the container one of the very first log lines should say something like
```
2021-03-13 12:02:19,061 INFO Included extra file "/usr/local/etc/supervisor/conf.d/http_server.conf" during parsing
```

The lines
```
PUID=1000
PGID=1000
```
don't do anything. Everything inside the container runs as UID 0 root. You can map the container UID to whatever UID makes sense for your system using subordinate UID/GIDs. See https://docs.docker.com/engine/security/userns-remap/

**Comment by lloesche** [comment]
Some other notes on your env file:
```
UPDATE_CRON='*/15 * * * *'
BACKUPS_CRON='7 * * * *'
```
should not have `'` around the value in a Docker env file because the `'` becomes part of the actual value. No idea why they made it different from how the shell works. What you want is:
```
UPDATE_CRON=*/15 * * * *
BACKUPS_CRON=7 * * * *
```

You could also remove the following lines if you wanted:
```
SERVER_PUBLIC=true
SERVER_PORT=2456
UPDATE_IF_IDLE=true
SUPERVISOR_HTTP_USER=admin
BACKUPS=true
BACKUPS_DIRECTORY=/config/backups
```
as they are all the default values. Again, nothing to do with your supervisor http server issue, just if you wanted to make the config shorter.

**Comment by ageisen2000** [comment]
@lloesche thanks for the suggestion. I'll add that line to my compose file.

Just for some context -- I just have a quick and dirty shell script that restarts my server nightly on a cron job and then copies my backups to my cloud drive. I know that this is possible from inside of the container, but I want to keep the container itself updated as best as possible, and wanted to use rclone for the copying. Theres some other logic that I omitted for logging and things that I also do in this script.
```
docker-compose -f "/home/serviceworker/valheim/docker-compose.yml" down
docker-compose -f "/home/serviceworker/valheim/docker-compose.yml" pull

rclone copy /home/serviceworker/valheim/backups /mnt/gdrive/adam/valheim/backups --max-age 48h

docker-compose -f "/home/serviceworker/valheim/docker-compose.yml" up -d
```

Maybe docker-compose restart worked, but docker-compose down might not have.... I'll try with the grace period added and see how it works
