### ISSUE TITLE
Plans on ARM support?

### ISSUE THREAD

**Issue by keny91** [lloesche/valheim-server-docker#162]
Was planning on giving a new use to my RaspberryPi 4. However, the current image does not support 'ARM' based architectures.
The only workaround I have found is to install Windown directly in my Rasp. 

Are there any plans on extending architecture support?

**Comment by lloesche** [comment]
The Valheim server only comes as x86_64. As soon as they provide an ARM build I would use that. But Steamworks SDK is not available for ARM so it's not even up to the Valheim developers. Steam would have to do the first step.
Maybe since the new M1 Macbooks are ARM based there could be a chance. But I wouldn't get my hopes up anytime soon.
