### ISSUE TITLE
No interaction with world

### ISSUE THREAD

**Issue by andrejberg** [lloesche/valheim-server-docker#181]
We are using this docker on an Ubuntu 20 system. We are connecting via local Wifi only. Everything works perfectly until after 15-30 min player (3) start to "de-sync" with the server. One can run around but not interact properly with the environment. Reconnecting is the only way to solve it.

**Comment by lloesche** [comment]
Sounds more like a server than a container question. But maybe with some more info somebody can help.

Like what's the hardware the server is running on? Valheim likes lots of RAM (it'll happily take 10 GB although 4 is enough if it is allowed to swap) and two or more high clocked cores. Performance is also dependent on the slowest player for whatever reason. Like we host our server in EU and whenever a friend from Australia joins in everyone starts to lag. Though not to the extend you describe. But since you're saying you're on Wifi and I don't know the quality of your Wifi (are you living alone in the countryside or in an apartment complex with 30 other SSIDs competing for airtime) it's possible this could be an issue.

There is no general "start lagging after 15-30 minutes" that affects everyone if that was your question. Normally you should be able to play for 10h straight with no performance issues.

**Comment by andrejberg** [comment]
Server hardware has 8GB RAM with 2GB swap. I monitored the memory consumption and it is never above 30%. 

You have a point regarding the WiFi SSIDs. We live in the city centre. The server is connected via cable to the local network but I might check if this happens if the host uses LAN, too.

By now, I don't think it's a container problem as well. The container works great, thank you. Yesterday, we played 1,5 hours with no problems at all. And then de-sync after every 15 min and then it might happen that the problem persists after host reconnection. When this happens, I have to restart the server.

**Comment by lloesche** [comment]
We definitely noticed the server leaking resources after a while. I don't know if that's still the case but a couple of weeks ago when I first build the container it happened for sure and a restart would make everything smooth again. Though for us it happened only after like 2-3 days of running continuously. That's how the 5 AM `RESTART_CRON` was born. We just restarted the server once a day and the issues were gone for us.

**Comment by Addyvan** [comment]
@andrejberg  I've seen this issue before. 

I was able to fix it for a few buddies of mine by editing firewall settings on their router. I'll check what we had to edit and edit this comment.

**Comment by Addyvan** [comment]
@andrejberg Are other users able to see the player running around when they are desynced? 

I've also seen restarting the game fix this issue. It's a weird problem since it also sometimes only localizes itself to a portion of the world.

**Comment by lloesche** [comment]
@andrejberg were you able to figure out what caused the lag and desync? Is it still an issue?

**Comment by andrejberg** [comment]
Yes, it was a network issue. We have now connected all machines via LAN and the problem is solved completely. I guess it is the crapy 8-year-old router that is not able to provide a stable WiFi signal. Thank you @lloesche and @Addyvan for your help.
