### ISSUE TITLE
When does PRE_RESTART_HOOK execute exactly?

### ISSUE THREAD

**Issue by aconstantinou-cmd** [lloesche/valheim-server-docker#212]
Hi, Ive passed the -e PRE_RESTART_HOOK with my curl command to the discord server, but I cant see or determine when exactly this event triggers? Hope you can help

**Comment by lloesche** [comment]
Here is where the hook gets executed:
https://github.com/lloesche/valheim-server-docker/blob/48565667d782b920fc5315c0ed297ff9127197c7/valheim-updater#L192-L194

This happens when the valheim-updater has found and downloaded a server (or ValheimPlus if active) update and needs to restart the server.
Maybe we should more fittingly call it "PRE_UPDATE_RESTART_HOOK" or something like that.

**Comment by aconstantinou-cmd** [comment]
Ahh that makes sense, thank you so much lloesche.
