### ISSUE TITLE
ValheimPlus directory not beeing created (Synology)

### ISSUE THREAD

**Issue by Rippa84** [lloesche/valheim-server-docker#233]
The ValheimPlus env variable is set to true, but the directory won't be created. Using a Synology DS918+.
![Screenshot 2021-03-17 110343](https://user-images.githubusercontent.com/80821005/111450264-84130e80-8710-11eb-8c87-f1876f1e8d88.jpg)

**Comment by InB4DevOps** [comment]
Try to also set this env var:
`VPCFG_Server_enabled=true`

**Comment by Rippa84** [comment]
Unfortunately this did not solve the problem

![Screenshot 2021-03-17 113134](https://user-images.githubusercontent.com/80821005/111454047-82e3e080-8714-11eb-97b2-f07113f67db3.jpg)

**Comment by Rippa84** [comment]
Also tried using 1 instead of true, as this is working for SERVER_PUBLIC

**Comment by lloesche** [comment]
Using `1` won't work. You should use `true/false` everywhere. Even for `SERVER_PUBLIC`. The `0/1` is only something the valheim server uses for the `-public` flag but no other part of the container understands it.

Couple of ideas:
The valheimplus config directory is only created during ValheimPlus installation. Did you previously install ValheimPlus and then delete the valheimplus config directory so that now on startup it finds the installation of ValheimPlus and doesn't create the config directory?

Does the valheim container have write permissions to this directory? I mean it must have had at one point because it was able to create those config files, but maybe permissions changed since then?

Can you post the entire startup log file? It should have the info we need.

I also see that you're still running on a very old version of the container (can tell from the startup command `/usr/sbin/supervisor` which in new versions is `/usr/local/sbin/bootstrap`).
Synology has a quirk where they remember the old startup command even when you update the image.
You should delete the container, download the latest version of the image and recreate it as described here: https://github.com/lloesche/valheim-server-docker#error-after-download-of-new-container-image

**Comment by Rippa84** [comment]
Deleting the old container and recreating on latest version fixed it. Thanks for the fast help.
