### ISSUE TITLE
Update check occasionally disconnects users and causes server to need manual restart

### ISSUE THREAD

**Issue by daviddob** [lloesche/valheim-server-docker#244]
It seems that every once in a while (maybe once a day) on the turn of the hour XX:00 the update check believes the server has no players online even though there are 2-3 active. It then takes the server down and it fails to initially come up cleanly (at least it does not appear in the server browser again until about 10mins later on the dot and there are some timeouts in the logs). This seems like similar behavior to #178 - though the machine has 4CPU cores @2.3GHz and 8GB ram allocated and never appears to even get close to those resources. 

Attached are the relevant server logs - let me know if there's anything else you want me to grab/change to test. Overall its been really solid and stable besides this hiccup.

[valheim-server.log](https://github.com/lloesche/valheim-server-docker/files/6174957/valheim-server.log)

**Comment by lloesche** [comment]
Ok went over the entire log. Here's what's happening:

It's not the update check disconnecting players it's the daily 5 AM restart. See `RESTART_CRON` in [the README](https://github.com/lloesche/valheim-server-docker#environment-variables).

The update check just happens to run at the same time (every 15 minutes) and because the server has already been restarted by the daily restart cron it sees that no players are currently connected and runs. Which is all correct behavior. If 5 AM in the container is not 5 AM local time set `TZ` to the correct value for your time zone. The default is [`UTC`](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).

From the logs it looks like your server is back after 30 Seconds not 10 minutes.
```
2021-03-20 05:00:27 [136710] (DEBUG) Waiting for server to listen on port 2456
```
Once this message stops appearing in the log the server is back online. As to when the server shows up in the server browser again, that's a different story and completely Steam related. Has nothing to do with the server or container. You will be able to reconnect after 30 seconds. Just [add the server as a Steam favorite](https://github.com/lloesche/valheim-server-docker#steam-server-favorites--lan-play) and you'll be good to go.

The only timeout I see is Steam failing to connect to its update servers.
```
ERROR! Timed out waiting for AppInfo update.
2021-03-20 05:01:11 [31] (ERROR) Failed to update Valheim server from Steam - however an old version was found - trying to start
```
This might also explain why it takes long for the server to show up in server browser again.
As to why that is is something for you to figure out. It has nothing to do with the container. Could be an intermittent network or Steam issue.

**Comment by daviddob** [comment]
Awesome, thanks! I noticed that the time was in UTC which usually I don't mind though I somehow totally overlooked the RESTART_CRON variable. I'll keep looking into why the steam errors are coming up and take a couple packet captures to see what's happening and post back if I come up with anything conclusive. Thanks for the quick answer!

**Comment by lloesche** [comment]
FYI in the latest container version I committed https://github.com/lloesche/valheim-server-docker/commit/82c81095301165b286442a1245dddc2bf6002f7e which makes it so that by default the daily restart is only performed when no players are connected to the server. Similar to how the update check works.
