### ISSUE TITLE
Server restart at 12AM UTC daily

### ISSUE THREAD

**Issue by mixm1xmix** [lloesche/valheim-server-docker#253]
I am trying to set the server to only restart when no players are connected, and during the early AM hours. Here's what I've set in the ENV variables on my Synology NAS docker config

RESTART_CRON 0 5 * * *
BACKUPS_CRON 0 * * * *
UPDATE_CRON 15 */2 * * *
UPDATE_IF_IDLE true
TZ America/Halifax

Despite the TZ, my local logs are showing UTC, so I just read them as 3 hours ahead of me. The server seems to restart at 00:00, as my logs indicate a rollover at 03:00. This is 11pm for most of my connected players and they are getting upset :)

I can't tell if I am reading your config wrong, because I've set the restart for 5am, which even if it doesn't respect my TZ, would be 2am local time, not midnight.

Also I cannot get the discord webhook to populate. Uncertain if I need to change the Username in the PRE_RESTART_HOOK template. I've created webhooks before so the discord end is set.

Great work on this container, it's running quite well otherwise!

**Comment by lloesche** [comment]
What does `date` inside the container say?

**Comment by mixm1xmix** [comment]
the logs show UTC time - currently 9:15pm.

**Comment by lloesche** [comment]
I understand that, but the question is what does running the `date` command inside the container output?

Should be something like `Mon Mar 22 05:21:06 ADT 2021` (if properly configured) or `Mon Mar 22 08:20:21 UTC 2021` (if not properly configured).

**Comment by lloesche** [comment]
Side note: I just merged https://github.com/lloesche/valheim-server-docker/commit/82c81095301165b286442a1245dddc2bf6002f7e which makes it so that the daily restart by default is only performed when no players are connected. So if you pull the latest version of the image your disconnection problem will be gone.

We should still figure out why the time zone is off in your container.

**Comment by mixm1xmix** [comment]
Sorry about that, yes, running date in an executed container shows ADT correctly
Mon Mar 22 12:50:03 ADT 2021

I don't mind the TZ being off so long as the server isn't rebooting during connections. thanks!

**Comment by mixm1xmix** [comment]
It seems the docker container continues to restart at 12AM UTC (3AM local time). It did so when I set the update_if_idle flag to true, and also when I subsequently set restart_cron to blank, attempting to disable the restart entirely. I'm likely going to blow the container away and try again, as I have no idea what might be causing this. No other containers have this behaviour and I am keeping this one updated as all others via watchtower. thanks for your help.

**Comment by lloesche** [comment]
@mixm1xmix setting `RESTART_CRON` blank should turn off any restarts. You can confirm by running
```
$ docker exec -it valheim-server crontab -l
0 * * * * [ -f "/var/run/valheim-backup.pid" ] && kill -HUP $(cat /var/run/valheim-backup.pid)
*/15 * * * * [ -f "/var/run/valheim-updater.pid" ] && kill -HUP $(cat /var/run/valheim-updater.pid)
0 5 * * * /usr/local/bin/valheim-is-idle && /usr/local/bin/supervisorctl restart valheim-server
```
That last line containing `restart valheim-server` will not be listed when `RESTART_CRON` is set to an empty string.

**Comment by mixm1xmix** [comment]
Deleted and started a new container with this script, same reboot at 12AM local time (AT). No idea why this keeps happening.

sudo docker create \
  --name=valheim-server \
  --cap-add=sys_nice \
  --restart unless-stopped \
  -e PUID=1026 \
  -e PGID=100 \
  -e TZ=America/Halifax \
  -p 2456-2458:2456-2458/udp \
  -v /volume1/docker/configs/valheim:/config \
  -e SERVER_NAME="mixmix" \
  -e WORLD_NAME="valhallaheim" \
  -e SERVER_PASS="<pass>" \
  -e RESTART_CRON="0 6 * * *" \
  -e BACKUPS_CRON="*/30 * * * *" \
  -e UPDATE_CRON="0 */6 * * *" \
  -e BACKUPS_DIRECTORY="/config/backups" \
  -e BACKUPS_MAX_AGE=7 \
  -e RESTART_IF_IDLE=true \
  -e UPDATE_IF_IDLE=true \
  -e VALHEIM_PLUS=true \
   lloesche/valheim-server
   
   $ sudo docker exec -it valheim-server crontab -l
*/30 * * * * [ -f "/var/run/valheim-backup.pid" ] && kill -HUP $(cat /var/run/valheim-backup.pid)
0 */6 * * * [ -f "/var/run/valheim-updater.pid" ] && kill -HUP $(cat /var/run/valheim-updater.pid)
0 6 * * * /usr/local/bin/valheim-is-idle && /usr/local/bin/supervisorctl restart valheim-server

**Comment by lloesche** [comment]
Ok this output makes sense because you are setting `-e RESTART_CRON="0 6 * * "`. What happens if you set `-e RESTART_CRON=""`? The `crontab -l` should then only return two lines. If the server is then still rebooting every day at 12 AM it's not a container issue but something external doing the restart.

Unrelated but I would also add a data volume like e.g. `-v /volume1/docker/data/valheim:/opt/valheim` to significantly speed up startup times.

I see that the cron shows a call to `/usr/local/bin/valheim-is-idle` as a condition for restarting the server. Is your server still being restarted with players connected? If so then it's also pretty safe to say that it's not the cron restarting the server.

Can you attach a complete startup log? I have a feeling that maybe you have an issue similar to #272 
Their server always restarted whenever an update check ran. The root cause was that the update check consumed some additional memory and then the Kernel's OOM killer killed the valheim-server as the heaviest user of RAM.

**Comment by mixm1xmix** [comment]
you are correct, when I removed the restart_cron flag crontab -l returned 2 results. I have 16Gb of ram in this NAS, so I do not think it's a resource choke, but hard to tell. 

I added the volume to speed up launch, thanks.

The server is indeed restarting with players connected.

startup log:

[valheim-server.zip](https://github.com/lloesche/valheim-server-docker/files/6218993/valheim-server.zip)

**Comment by lloesche** [comment]
@mixm1xmix 16 GB is plenty. If the container is allowed to use 4 GB that should be sufficient. All the issues we saw were on systems where the container had 2 GB or less.

The startup log looks fine. Nothing out of the ordinary. Next time the server restarts unexpectedly add another log to this issue and we should be able to get more info as to why and how the server is getting restarted.

**Comment by mixm1xmix** [comment]
Looks like the rebuild may have fixed my issues. I had some cache RAM in the NAS that reached end of life, it may have had something to do with this, but I'm unsure. thanks again for all your help!

**Comment by lloesche** [comment]
@mixm1xmix sure thing. If it happens again reopen or create a new issue with the new logs.
