### ISSUE TITLE
Document Docker tags

### ISSUE THREAD

**Issue by schildbach** [lloesche/valheim-server-docker#260]
Specifically, what's the difference between `latest`, `main` and `dev`? Is there a stable tag?

**Comment by lloesche** [comment]
`main` and `dev` are names of the git branches. Dockerhub automatically builds for whatever branch names there are in the git repo. `latest` is the latest `main` branch build. So `main` and `latest` should be identical.
There is no `stable` because what would that even mean in the context of an Early Access game?
I typically merge larger changes into `dev` first and then test them on our server for a day or two before merging into main. So `dev` is definitely more unstable than main.

**Comment by schildbach** [comment]
I think your last sentence sums it up pretty well. Guess I will follow the main tag then, as it's as stable as possible.
