### ISSUE TITLE
consider adopting semver for container tags?

### ISSUE THREAD

**Issue by billimek** [lloesche/valheim-server-docker#274]
The current images rely on the `latest` tag which doesn't offer discoverability or information about updates.  It would be really useful if (maybe in addition to `latest`) the published images included semver versioning for the tag.

**Comment by lloesche** [comment]
So, long reply as we've had the discussion here and there but never in condensed form.

One of the first messages the container outputs is e.g.
```
Mar 27 09:53:25 /supervisord: valheim-bootstrap DEBUG - [18] - Running commit 2675b8b0803a6f5f5ce2002325e2a4409e27a060
```

That information is stored in `/usr/local/etc/git-commit.HEAD`. The purpose is to figure out which version of the container a user is running when they report an issue.

I might add something that periodically checks if you are running the latest commit of the container. But I have zero interest in introducing arbitrary semantic versions for a container that runs an early access game server and updates it at runtime.

Take the following scenario. We tag the container e.g. `0.5.0-stable` and a user pins that version on their system. It works for a while but in a months or two Iron Gate (or more likely ValheimPlus) does a breaking change. The container updates to the latest version of the game server every 15 minutes. So that supposedly `stable` container now has downloaded a game server version it can't handle and is no longer stable. At that point what is the worth of that `0.5.0-stable` semver?

The solution also isn't to not update the game server every 15 minutes. Because the user's Steam will update their Valheim desktop client as soon as an update is released and at that point you'd have an outdated server with an up to date client that can no longer connect.

My feeling on the subject is as long as the game is early access we'll update the container in lockstep with any Valheim releases and users will have the best experience if they just run `:latest`. When they have container trouble we can debug it using the commit hash. Experimental features are already being incubated in the `:dev` branch/tag and the general mantra for working on this container is to make absolutely everything backwards compatible and not introduce any breaking changes.
That is why it contains things like the `fake-supervisord` file or that path migration info in `valheim-bootstrap` and still supports `UPDATE_INTERVAL` and `BACKUP_INTERVAL` even though they've been replaced by cron equivalents. You can run the latest version of the container with the very first container's config and it'll translate gracefully. I put user convenience above all else as I know that this container is in use by a lot of non-technical users and I want them to have a good experience.

@TheCatLady and I had discussions whether we should tag each image build with the commit hash so you could go back and look at old image builds. My feelings on that subject are it's a waste of Github's and Dockerhubs disk space.

Tagging the issue with `wontfix` but leaving open as I'm always open to compelling arguments.

**Comment by TheCatLady** [comment]
> @TheCatLady and I had discussions whether we should tag each image build with the commit hash so you could go back and look at old image builds. My feelings on that subject are it's a waste of Github's and Dockerhubs disk space.

I actually am not sure what disk space you're referring to? 😅 There isn't really any negative to tagging images with the hash.

**Comment by lloesche** [comment]
> what disk space you're referring to

If we tag each image build with a unique hash it'll stay around forever on Github's servers taking up unnecessary space. It's the reason Docker [introduced a retention limit](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/).
I'm saying that's a waste because realistically nobody will ever pull those old builds ever again. And if they wanted to they could just build it locally from the git hash.

**Comment by TheCatLady** [comment]
> If we tag each image build with a unique hash it'll stay around forever on Github's servers taking up unnecessary space. It's the reason Docker [introduced a retention limit](https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/).

I'm not sure what you mean by that?  Tagging the image doesn't have any effect on its retention, it's just a label that is applied to that built image, basically.

**Comment by lloesche** [comment]
> Tagging the image doesn't have any effect on its retention

Never wrote that it has. What I wrote is, people tagging every single commit is one of the reasons Dockerhub retention rules had to be introduced in the first place.

But let's step back 🙂 
Are we in agreement, that the container consumes around 200 MB to store?
Let's ignore for a moment, that these 200 MB are compressed and that there's uncompressed layers kept around for build caching, and all kinds of other possible optimizations like block level deduplication that could go on on the FS level.

If we are storing a `dev`, and `latest` tag of it that's roughly 400 MB, right? And no matter how often we merge/commit something that number is a constant. It does not increase as we're always overwriting the existing tags thereby dereferencing the old one.

Since the inception of this repo we've pushed 170 commits. That averages around 3.54 commits per day. So if we were to tag each image build with the unique commit hash we would increase our storage consumption by 708 MB per day or 250 GB per year.
Accounting for both, GHCR and Dockerhub instead of 0.8 GB we would consume half a TB of storage on the Github and Dockerhub servers for no good reason whatsoever.

Just for fun consider for a moment the impact of 190 Million Github repos doing the one or the other thing. As in having 2 static tags vs. tagging every commit at the same rate as we are. That is a constant 145 PB of storage vs 90,599 PB per year. Then consider that those storage SSDs are cycled out after 3 or so years and their PCBs land in some landfill.

Hence my feeling we'd just be producing waste by tagging each image with a unique hash.

**Comment by TheCatLady** [comment]
@lloesche Actually, nothing is getting "overwritten" when you publish a new image with an existing tag. The existing images persist, just with the `latest` tag removed.  So tagging with the has really won't have any impact on storage usage.

**Comment by lloesche** [comment]
@TheCatLady I beg to differ. See https://hub.docker.com/r/lloesche/valheim-server/tags
There are only three digests being referenced by our three tags `latest`, `dev` and `main`.
Once a tag is no longer referencing a digest any unreferenced image layers are being released for garbage collection and the storage eventually freed

**Comment by TheCatLady** [comment]
> @TheCatLady I beg to differ. See https://hub.docker.com/r/lloesche/valheim-server/tags
> There are only three digests being referenced by our three tags `latest`, `dev` and `main`.
> Once a tag is no longer referencing a digest any unreferenced image layers are being released for garbage collection and the storage eventually freed

Actually, they aren't. 😅  See this Docker blog post: https://www.docker.com/blog/advanced-image-management-in-docker-hub/
> This new manifest will be given the tag you specify when you push, such as bengotch/simplewhale:latest. But this does not mean that all of those old manifests which point at the previous layers that made up your image are removed from Hub. These are still here, there is just no way to easily see them or to manage that content. You can in fact still use and reference these using the digest of the manifest if you know it. You can kind of think of this like your commit history (the old digests) to a particular branch (your tag) of your repo (your image repo!). 

And on GitHub, you can view all published images (including untagged images) here: https://github.com/users/lloesche/packages/container/valheim-server/versions?filters%5Bversion_type%5D=all

**Comment by lloesche** [comment]
> Actually, they aren't. 😅 See this Docker blog post: https://www.docker.com/blog/advanced-image-management-in-docker-hub/

What you linked is for paid plans. I remember sometime last year they announced that they've only paused enforcement of image retention until mid 2021 but their overall goal is to reduce resource consumption (or have you pay for it). So those unreferenced digests will be removed eventually.

**Comment by TheCatLady** [comment]
> What you linked is for paid plans. I remember sometime last year they announced that they've only paused enforcement of image retention until mid 2021 but their overall goal is to reduce resource consumption (or have you pay for it). So those unreferenced digests will be removed eventually.

The blog post is about advanced image management features for paid plans, but the information about what happens when you push a new image with an existing tag applies to all Docker Hub repositories.

> ```
> We are pausing enforcement of the changes to image retention until mid 2021.
> Two months ago, we announced a change to Docker image retention policies
> to reduce overall resource consumption.
> ...
> Docker is focusing on consumption-based subscriptions
> ```

Image retention limits would apply regardless of tags. Tagged images are still subject to the same policies if they are inactive.

Basically, the untagged image manifests on Docker Hub are not treated any differently than tagged ones with regards to image retention.  It won't impact resource/storage usage in any way.

I personally think it's nice to tag with the commit hash, since it makes it easier for a user to pull a specific version of the Docker image. If a particular image becomes inactive (no pull activity for X amount of time), Docker hub will still prune it regardless of the tag.

**Comment by lloesche** [comment]
> The blog post is about advanced image management features for paid plans, but the information about what happens when you push a new image with an existing tag applies to all Docker Hub repositories.

Right, what I meant to point out is their intention. They say they want to reduce resource consumption, in other words they want to spend less money on things they don't make money from. Which I think is fair.
With a paid plan you will continue to be exempt from any retention rules. With a free plan you can be sure they'll work hard on freeing those resources as soon as possible. They just paused that new rule after the backlash they received when announcing it.

> I personally think it's nice to tag with the commit hash, since it makes it easier for a user to pull a specific version of the Docker image.

I understand that use case I just don't see which persona is going to do that on such a regular basis it would justify binding those resources for.

> Docker Hub will still prune it

I received feedback from Docker that we're going to be covered under the open source program so we'll be exempt from those rules. I'll have to accept some "Joint Marketing Program" though and currently clarifying if our push to GHCR is in conflict with that. If it is then we'll complete the full move to GHCR and update all documentation to point to it instead of Dockerhub.

**Comment by billimek** [comment]
@lloesche I wasn't fully aware that the valheim server container was dynamically updating the server software at runtime.  Given that, and given that it's still early-access like you say, it doesn't seem to provide a ton of value versioning the image.

My main concern was needing to periodically pull a fresh 'version' of the `latest` tag in order to pick up whatever changes are required.  It doesn't look like that is as important given the dynamic auto-updating nature of this.  I run valheim as a kubernetes pod and, in that world, using statically-tagged images (like `latest`) are not a best practice because updates to the container image are opaque.

Happy to close this issue unless we want to keep it open for more discssion.

**Comment by TheCatLady** [comment]
> Right, what I meant to point out is their intention. They say they want to reduce resource consumption, in other words they want to spend less money on things they don't make money from. Which I think is fair.
> With a paid plan you will continue to be exempt from any retention rules. With a free plan you can be sure they'll work hard on freeing those resources as soon as possible. They just paused that new rule after the backlash they received when announcing it.

Oh yes, I agree that it's fair for them to remove unused images.  Just wanted to point out that the current practice of not tagging with the hash doesn't reduce resource consumption in any way, unfortunately. Anyone can pull any previously published images from Docker Hub using the digest ID, even if they are hidden from view on the website.

> I understand that use case I just don't see which persona is going to do that on such a regular basis it would justify binding those resources for.

Again, wouldn't use/bind any additional resources. Would it be super useful?  Probably not.  But it also wouldn't result in increased resource consumption.  Once the image retention policy begins to be enforced, inactive images will still be removed even if they are tagged with the hash.  The additional tag really has no impact on resource usage.

Also, just to be clear -- I'm not advocating for tagging with the commit hash.  I just want to make sure that everyone is on the same page re: the implications of doing so.

> I received feedback from Docker that we're going to be covered under the open source program so we'll be exempt from those rules. I'll have to accept some "Joint Marketing Program" though and currently clarifying if our push to GHCR is in conflict with that. If it is then we'll complete the full move to GHCR and update all documentation to point to it instead of Dockerhub.

That's awesome!  However, I believe Docker Hub's Open Source program only lifts the pull rate limitations (which is not a bad thing!).  GHCR is pretty great, though. Even with pull limits, I don't see the harm in continuing to publish images to both repositories, especially since I'm sure there are users who have configured automatic image updates. We should update the README to help users decide which repository to use, however.

**Comment by lloesche** [comment]
Closing this as there's no semver related discussion going on.
