### ISSUE TITLE
Implementation of BepInExPack

### ISSUE THREAD

**Issue by lloesche** [lloesche/valheim-server-docker#282]
Hello 

Are there any plans to implement BepInExPack similar as the Valheim+ mod?
That would be a great way for easy mod module loading. 

[Mod Link](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/)

_Originally posted by @madhub0815 in https://github.com/lloesche/valheim-server-docker/discussions/279_

**Comment by lloesche** [comment]
@madhub0815 check `lloesche/valheim-server:dev` and specify `BEPINEX=true`. It'll download and install BepInExPack. Right now after adding plugins to the plugins directory whenever there is a Valheim Server update or a BepInExPack update it would get overwritten.
From your point of view, what would be better:
- being able to specify a list of mods to be automatically updated/downloaded and installed from https://thunderstore.io/
- having to manually install and update plugins in a volume mount

I can see use cases for both.

**Comment by madhub0815** [comment]
First i will thank you for the quick implementation. 

To set a list of plugin and get it auto updatet and downloaded would be great.
 
Because some plugins for example equipment and quick slots have to be there when a player is joining the server because if there is a server update and the plugin would not be there the player can not use the equiped amor. 

Therefore the admin have to react manuel and install plugins again wich may be not always possible? 

I will set up a test server later that day to test the general function.

**Comment by lloesche** [comment]
@madhub0815 ok makes sense. Maybe we should also build something that will make all plugins available to the user for download as one ZIP file? So that when the server auto updates like 50 plugins the user doesn't have to do that by themselves?
Do you know if Valheim Plugins are always within the `BepInEx/plugins/` folder? Or are some outside of this directory structure?

**Comment by madhub0815** [comment]
@lloesche Yes plugins should be all in the mentioned folder. The idea of auto update and installing these to clients directly is good but if clients are using a mod manager like "Thunderstore" not practicable. 

Because the folder of the modmanager is "C:\Users\WINDOWSUSER\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\MODMANAGERPROFILE\BepInEx\plugins" and plugins have to be managed in the mod manager like turn on/off install or uninstall or just play vanilla without any mods. Because of that you can have mods without changing/editing files in the game directory itself.

Therefore i think it will be easier to give the responsibility of plugins are up to date to the clients themselves by using the mod manager.

I  just set up a test server by pulling lloesche_valheim-server:dev but in the startup log i can not see any presence of BepInEx so far? Also there is no BeInEx folder in the server directory being created. I just used attached EVNs

![image](https://user-images.githubusercontent.com/49038539/112976586-56d55000-9155-11eb-837c-08309e0e520f.png)

**Comment by lloesche** [comment]
The `BEPINEX=true` is missing in your config.
Also all the other true/false fields will all be ignored and using defaults because they have wrong capitalization.
It needs to be literally `true` not `TRUE` or `True`.

**Comment by madhub0815** [comment]
Just pulled the latest dev version. All seems to go fine until line 1396 of the attached log file lots of Fallback handler error come up.

[_Valheim_Test_logs.txt](https://github.com/lloesche/valheim-server-docker/files/6230015/_Valheim_Test_logs.txt)

Maybe it will help you with your further development.

I copied 3 plugins to the server to test functionality and restarted the container.
The plugin load starts in line 629 of the log file below with "Fallback handler could not load library" errors and they are not working.
[_Valheim_Test_logs (1).txt](https://github.com/lloesche/valheim-server-docker/files/6230079/_Valheim_Test_logs.1.txt)

i hope the information are helpful to you.

**Comment by lloesche** [comment]
Those `Fallback handler` messages don't mean anything. In ValheimPlus you'll see them all over the place.

**Comment by lloesche** [comment]
Actually in ValheimPlus you might have never seen them because there we just filter them away because they are so annoying:
https://github.com/lloesche/valheim-server-docker/blob/e05ae2bf622866eb729a23a0b99b18cb42ca4470/defaults#L88-L90

I can add that for BepInEx as well to get rid of the noise.

**Comment by lloesche** [comment]
Okay the server will now install any plugins in `/config/bepinex/plugins/` whenever BepInExPack is installed/updated.
This allows you to use mod from any sources. Be it thunderstore, Nexus mods, local builds or anywhere else.

As a side effect this also allows ValheimPlus users to add additional plugins to `/config/valheimplus/plugins/`.

**Comment by madhub0815** [comment]
Thank you for your great work. Will test it tomorrow. 👍
