### ISSUE TITLE
Only backup .db.old because only that is guaranteed to be consistent

### ISSUE THREAD

**Issue by ibex-are-goats** [lloesche/valheim-server-docker#388]
Valheim-server-docker documentation says:

> Beware that backups are performed while the server is running. As such files might be in an open state when the backup runs. However the worlds/ directory also contains a .db.old file for each world which should always be closed and in a consistent state.

So Valheim creates a trusted, consistent, and frequent .db.old backup. That's what we should be backing up right? Not that PLUS the inconsistent redundant active database right next to it?

**Comment by TheHades** [comment]
See https://github.com/lloesche/valheim-server-docker/pull/372#discussion_r652164895

**Comment by lloesche** [comment]
@ibex-are-goats the `.db` files are in all likelihood fine. Valheim only writes those files once every 20 minutes if I remember correctly. So the chance of backup running right during those 500ms or so when the server saves the world is pretty slim. The `.db` files are newer than the `.old` ones which is why if you have to restore a world these would be the ones where you lose the least changes.

So I think it makes good sense to backup both, the `.db` and the `.old` files. In all likelihood you'll be able to restore from the newer `.db` but if not there's always the .old which is guaranteed to be consistent.
