### ISSUE TITLE
Inefficient use of space with bepinex or plus

### ISSUE THREAD

**Issue by kohanis** [lloesche/valheim-server-docker#410]
It's not actually necessary to use /opt/valheim/server with any mod option when we have /opt/valheim/dl/server, isn't it? And it's almost 1gb of space.

This can be excluded with a bit extra logic. Should I check later and send PR?

**Comment by lloesche** [comment]
The dl/server is also copied for vanilla not just when using mods.

It's how the system knows whether there was an update and needs to restart the server. Previous versions tried to parse the steamcmd output but that turned out to be unreliable on fast connections as you will not see any download/progress if the update takes less than 1s (on slow connections it prints the download status every couple of seconds). There was also a version where we used the appid metadata to determine if an update was downloaded and that also turned out to be unreliable. Don't remember the details. In the end we just decided to have a clean dl of the vanilla server and then rsync that into whatever runtime directory (vanilla, V+, BepInEx). That way we had a 100% reliable way of knowing if any files actually changed and whether the server needs to be restarted or not.
We also had a version where we used rsync with hard-links instead of copies so that the space is not actually occupied twice, but that didn't work on some NAS users filesystems.

This rsync mechanism is also used to keep multiple installs of vanilla, BepInEx and V+ up to date even when you're not using one of them right now. As in you could install V+ then switch back to vanilla, receive a valheim server update and it'll update both your vanilla install as well as the V+ install as long as you don't purposefully remove the V+ installation. Allowing you to seemlessly switch back and forth between vanilla and mods.

It's only 1 GB of space so we never saw a reason to try and optimize that further. That said if you find a way that works on all different NAS systems, different filesystems, detects updates 100% reliable and lets users switch between different installations (vanilla / V+ / bepinex) I'll happily merge a PR.

**Comment by kohanis** [comment]
Well, I needed to do update checks for my local project and... what's wrong with checking {steamcmd}/steamapps/appmanifest_896660.acf? With cached buildid. Or even comparting it with steamcmd.net data (https://api.steamcmd.net/v1/info/896660) without unnecessary steamcmd runs
