### ISSUE TITLE
Force world save before shutdown/restart

### ISSUE THREAD

**Issue by Do-while-Bacon** [lloesche/valheim-server-docker#59]
We discovered the hard way that restarting the Docker container will cause a rollback of the server world (20 minutes?) because it appears to only save the state on a periodic cadence.

Is there a way to manually force a save before executing a restart? Or, can I otherwise bring down the container in a way that will trigger a save?

A game "cheat" exists to perform a save, but I read that it doesn't work, and cheats allegedly can't be executed on a multiplayer server anyway?

Thanks!

**Comment by lloesche** [comment]
That is because of an outdated container image. If you pull the latest version the world will be saved on shutdown. Iron Gate changed the way the server is being shut down from creating a file to signal a shutdown to sending a SIGINT which broke the shutdown script. See https://github.com/lloesche/valheim-server-docker/issues/13
