### ISSUE TITLE
Stage update for later reboot

### ISSUE THREAD

**Issue by herver** [lloesche/valheim-server-docker#95]
Hello there,

I'm running a server using your container and it's working just fine, with just a minor possible improvement I will explain here:

The server is running 24/7 and I told my friends that every morning at ~05:30 the server will be restarted for maintenance, but I had the server restart itself this morning with the release of `0.146.8` (at 09:50 local time) without any prior warning and people were connected.

I understand that this is the default behaviour, but maybe this could be improved by adding a flag that would just stage the update, **but not restart the valheim server**, which will be taken care of by the daily restart.

This would help and manage users expectations (of course, if an update is released in the middle of the day, a manual action will be required to allow clients with the updated version to connect, but that's fine for me)

Thanks again for the nice work !

**Comment by lloesche** [comment]
@herver great suggestion! We'll improve the current situation.

Let me break down my thoughts on the issue of updates:

For Steam updates I feel it makes sense to apply them immediately because clients will generally get them pushed by Steam itself and the worst thing to have is an up to date client with an outdated server. That said Steam updates are more like a weekly, and once out of EarlyAccess monthly to quarterly occurrence. So I don't feel this is even the reason for this issue.

For V+ I suppose we could put something in that holds updates back. But I feel that's also a bit on V+ to improve. Maybe releasing three "stable" updates in three days means they weren't that stable to begin with and should be incubated a bit longer.
So I'm having a hard time justifying implementing a fix for something that should be improved somewhere else.

Regardless of those two aspects I had been planning to move away from the `UPDATE_INTERVAL` and over to a cron scheduled `UPDATE_CRON` so that update checks happen at predictable times.
With the introduction of the `RESTART_CRON` I added a BusyBox `crond` to the container anyways so we might as well use it for update checks. I just hadn't come up with a good way of not breaking backwards compatibility.
I suppose we'll have to convert the `UPDATE_INTERVAL` seconds to one or more cron schedules. Which is a non-trivial task to solve correctly. Like, `3600` is an easy `0 * * * *`. But suppose someone uses `5400` (ever 90 minutes). That's two schedules `0 0-21/3 * * *` and `30 1-22/3 * * *`, etc.
But maybe it is enough to round up/down to the closes single schedule and give the user a message at startup notifying them about the schedule that had been generated.

My thoughts on the issue 🙂

**Comment by jordannick** [comment]
My friends and I encountered this the other night when an update was pushed mid-evening. But I'd also agree that it's best that server-client versions are kept in sync as often as possible.

I'd propose an alternative solution, like an automated broadcast message: "The server is restarting in XX minutes for an update to version YY." Unfortunately, there does seem to be support in-game (yet) for that kind of feature either.

**Comment by lloesche** [comment]
@herver I just merged https://github.com/lloesche/valheim-server-docker/pull/100 which should help you in making these update checks more predictable. There is now `UPDATE_CRON` which defaults to every 15 minutes but can be changed to match the server restart schedule or anything else. The cron is only installed if `UPDATE_INTERVAL` has not been specified.

**Comment by lloesche** [comment]
@jordannick That would be fantastic. Some local socket that allows to display messages to all players.

**Comment by herver** [comment]
Thanks for the great work ! that was blazing fast and fits what I had in mind
❤️
